apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-docserver-lb
  namespace: onlyoffice
  labels:
    app: onlyoffice-docserver
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: onlyoffice-docserver
