apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onlyoffice-docserver.fullname" . }}
  labels:
    {{- include "onlyoffice-docserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "onlyoffice-docserver.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "onlyoffice-docserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "onlyoffice-docserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: documentserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.database.existingSecret }}
            - secretRef:
                name: {{ .Values.redis.existingSecret }}
          env:
            - name: JWT_ENABLED
              value: {{ .Values.env.JWT_ENABLED | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: onlyoffice-jwt
                  key: JWT_SECRET
            - name: JWT_HEADER
              value: {{ .Values.env.JWT_HEADER | quote }}
            - name: JWT_IN_BODY
              value: {{ .Values.env.JWT_IN_BODY | quote }}
            - name: WOPI_ENABLED
              value: {{ .Values.env.WOPI_ENABLED | quote }}
            - name: ALLOW_PRIVATE_IP_ADDRESS
              value: {{ .Values.env.ALLOW_PRIVATE_IP_ADDRESS | quote }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.data.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.data.mountPath }}
            {{- end }}
            {{- if .Values.persistence.logs.enabled }}
            - name: logs
              mountPath: {{ .Values.persistence.logs.mountPath }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim }}
        {{- end }}
        {{- if .Values.persistence.logs.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.logs.existingClaim }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
